language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic" ROS_REPO=ros              UPSTREAM_WORKSPACE=.travis.rosinstall.kinetic
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=.travis.rosinstall.kinetic
    - ROS_DISTRO="kinetic" CLANG_FORMAT_CHECK=file
    - ROS_DISTRO="kinetic" PRERELEASE=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" ROS_REPO=ros
    - env: ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
